### ISSUE TITLE
hypershell dependency tiny-configs at npm links to repo which creates a 404 at GH

### ISSUE THREAD

**Issue by pmario** [holepunchto/hypershell#24]
Hi folks, 
hypershell lists [tiny-configs](https://www.npmjs.com/package/tiny-configs) as a dependency. It seems the repo does not exist anymore. The link at npm creates a 404 at GitHub. .. Should it be updated?

**Comment by LuKks** [comment]
Sorry about that, the repo is now public!
https://github.com/LuKks/tiny-configs

Notice that the content was always visible on NPM:
![image](https://user-images.githubusercontent.com/12686176/221906332-e0092c72-8222-458d-b5af-53371522c5e9.png)

Thanks for your notice!
