### ISSUE TITLE
Server disallows connection from client 

### ISSUE THREAD

**Issue by warmachinesocial** [holepunchto/hypershell#36]
Even when we add the peer ID under authorized_peers it still doesn't connect?

**Comment by LuKks** [comment]
Can you try with hexadecimal format for the public keys? That should 100% work

Will add support for z32 keys soon

**Comment by nishp77** [comment]
Thanks @LuKks it's working now, however I have a question as to how we can server this in background or run during boot? For now a script would work but just asking

**Comment by LuKks** [comment]
Which operative system?

For Linux (Ubuntu) I always do as follows:

```
sudo nano /etc/systemd/system/project-name.service
```

```
[Unit]
After=network.target

[Service]
ExecStart=/usr/bin/node /home/root/project-name/app.js
ExecReload=/bin/kill -s INT $MAINPID
User=root
Group=root
WorkingDirectory=/home/root/project-name

TimeoutSec=0
RestartSec=2
Restart=always

StartLimitBurst=3
StartLimitInterval=60s

[Install]
WantedBy=multi-user.target
```

```
sudo systemctl start project-name
sudo systemctl enable project-name # Automatic boot on start
```

**Comment by nishp77** [comment]
I went with pm2

**Comment by nishp77** [comment]
Minor issue that's when we disconnect we need to log to console just for clarity

**Comment by LuKks** [comment]
It does log when the peer disconnects

![image](https://github.com/holepunchto/hypershell/assets/12686176/b5a58d46-2028-409f-bf27-b5e82645ba4f)

I might add colors for the firewall logs, green vs red
